import { Box, Button, Drawer, DrawerBody, DrawerCloseButton, DrawerContent, DrawerFooter, DrawerHeader, DrawerOverlay, FormControl, FormLabel, HStack, IconButton, Image, Input, Text, VStack } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { Trash2 } from 'lucide-react';
import { ApiState, useAuth, useHistory, useProfile, useRefreshStudentData } from '@/api/runtime';
import { conversationsApi } from '@/api/conversations';
import { conversationHref } from '@/api/chatSession';
import { profileApi } from '@/api/profile';
import { uploadsApi } from '@/api/uploads';
import type { ProfileUpdateInput } from '@/types/view';

export function ChatHistoryDrawer({isOpen,onClose}:{isOpen:boolean;onClose:()=>void}) {
 const query=useHistory(); const cache=useQueryClient(); const navigate=useNavigate(); const [search,setSearch]=useState(''); const [error,setError]=useState<unknown>(null); const [deleting,setDeleting]=useState<string|null>(null);
 async function remove(id:string) { if(deleting)return; setDeleting(id);setError(null);try{await conversationsApi.delete(id);cache.removeQueries({queryKey:['conversation']});await cache.invalidateQueries({queryKey:['conversations']});}catch(e){setError(e);}finally{setDeleting(null);} }
 return <Drawer isOpen={isOpen} onClose={onClose} placement="left" size="xs"><DrawerOverlay bg="rgba(7,31,53,.38)" backdropFilter="blur(2px)"/><DrawerContent color="white" bg="linear-gradient(165deg,#143A5B,#071F35)" maxW="350px"><DrawerCloseButton aria-label="關閉聊天紀錄"/><DrawerHeader>聊天紀錄</DrawerHeader><Box px="16px"><Input aria-label="搜尋聊天紀錄" placeholder="搜尋聊天紀錄" value={search} onChange={e=>setSearch(e.target.value)} bg="whiteAlpha.100"/></Box><DrawerBody><ApiState loading={query.isPending} error={error??query.error} retry={()=>void query.refetch()}/><VStack align="stretch" spacing="10px">{query.data?.pages.flatMap(page=>page.items).filter(x=>x.title.includes(search)).map(item=><HStack key={item.conversationId}><Button flex="1" minW={0} h="auto" py="12px" variant="ghost" whiteSpace="normal" justifyContent="flex-start" textAlign="left" _hover={{bg:'whiteAlpha.200'}} onClick={()=>{onClose();navigate(conversationHref(item.conversationId,item.mode));}}><Box><Text fontSize="13px">{item.title}</Text><Text mt="5px" fontSize="10px" opacity={.7}>{new Date(item.updatedAt).toLocaleString('zh-TW')}</Text></Box></Button><IconButton aria-label={`刪除聊天紀錄：${item.title}`} icon={<Trash2 size={15}/>} size="sm" variant="ghost" isLoading={deleting===item.conversationId} onClick={()=>void remove(item.conversationId)}/></HStack>)}{query.data?.pages.every(page=>page.items.length===0)&&<Text fontSize="13px">還沒有聊天紀錄。從一個問題開始吧。</Text>}{query.hasNextPage&&<Button isLoading={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>載入更多</Button>}</VStack></DrawerBody></DrawerContent></Drawer>;
}
const fields=[['nickname','暱稱'],['grade','年級'],['region','地區'],['familyOccupation','家庭工作'],['familyType','家庭型態'],['economicStatus','經濟狀況'],['otherIdentities','其他身分（以逗號分隔）']] as const;
export function ProfileDrawer({isOpen,onClose}:{isOpen:boolean;onClose:()=>void}) {
 const cache=useQueryClient();const query=useProfile();const {identity,logout}=useAuth();const refresh=useRefreshStudentData();const [draft,setDraft]=useState<Record<string,string>>({});const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);
 useEffect(()=>{if(query.data&&!editing)setDraft(Object.fromEntries(fields.map(([key])=>[key,Array.isArray(query.data![key])?(query.data![key] as string[]).join(', '):String(query.data![key]??'')])));},[query.data,editing]);
 async function save(){if(busy)return;setBusy(true);setError(null);try{const input:ProfileUpdateInput={nickname:draft.nickname,grade:draft.grade?Number(draft.grade):null,region:draft.region||null,familyOccupation:draft.familyOccupation||null,familyType:draft.familyType||null,economicStatus:draft.economicStatus||null,otherIdentities:draft.otherIdentities.split(/[,，]/).map(x=>x.trim()).filter(Boolean)};await profileApi.update(identity.userId,input);await refresh();await cache.invalidateQueries({queryKey:["session"]});setEditing(false);}catch(e){setError(e);}finally{setBusy(false);}}
 async function removeMemory(key:string){setError(null);try{await profileApi.deleteMemory(identity.userId,key);await refresh();}catch(e){setError(e);}}
 return <Drawer isOpen={isOpen} onClose={onClose} placement="bottom"><DrawerOverlay/><DrawerContent maxW="430px" mx="auto" borderTopRadius="24px" maxH="90dvh"><DrawerCloseButton aria-label="關閉關於我"/><DrawerHeader>關於我<Text mt="4px" fontSize="12px" color="gray.500">讓學伴找到適合你的學習與生活資源</Text></DrawerHeader><DrawerBody overflowY="auto"><ApiState loading={query.isPending} error={error??query.error} retry={()=>void query.refetch()}/>{query.data&&<VStack align="stretch" spacing="11px">{fields.map(([key,label])=><FormControl key={key}><FormLabel fontSize="12px">{label}</FormLabel><Input value={draft[key]??''} type={key==='grade'?'number':'text'} isReadOnly={!editing} onChange={e=>setDraft({...draft,[key]:e.target.value})} bg={editing?'white':'#F5F9FA'}/></FormControl>)}<Box bg="brand.50" p="13px" borderRadius="13px"><Text fontSize="12px" fontWeight="800">已同意記憶</Text>{query.data.memories.map(memory=><HStack key={memory.key} mt="8px"><Text flex="1" fontSize="12px">{memory.displayValue}</Text><Button size="xs" variant="outline" onClick={()=>void removeMemory(memory.key)}>刪除記憶</Button></HStack>)}{!query.data.memories.length&&<Text fontSize="12px" mt="6px">尚無記憶。聊天中同意後才會儲存。</Text>}</Box><Button size="sm" variant="ghost" onClick={logout}>登出／切換身分</Button></VStack>}</DrawerBody><DrawerFooter gap="8px">{editing?<><Button variant="ghost" onClick={()=>setEditing(false)}>取消</Button><Button flex="1" isLoading={busy} onClick={()=>void save()}>儲存資料</Button></>:<Button w="full" isDisabled={!query.data} onClick={()=>setEditing(true)}>編輯資料</Button>}</DrawerFooter></DrawerContent></Drawer>;
}
export function AuthenticatedImage({id}:{id:string}) {
 const [url,setUrl]=useState('');const [error,setError]=useState<unknown>(null);
 useEffect(()=>{const control=new AbortController();let objectUrl='';void uploadsApi.downloadContent(id,{signal:control.signal}).then(value=>{if(control.signal.aborted)return;objectUrl=URL.createObjectURL(value.blob);setUrl(objectUrl);}).catch(e=>{if(!control.signal.aborted)setError(e);});return()=>{control.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[id]);
 return url?<Image src={url} alt="已上傳的題目圖片" maxH="220px" objectFit="contain" borderRadius="12px"/>:<ApiState loading={!error} error={error}/>;
}
